### ISSUE TITLE
Error: Cannot find module 

### ISSUE THREAD

**Issue by Joeheim** [jvolker/miq-nz-booking-tools#10]
Hi there,

thanks for your hard work.

Unfortunately after following the install instructions i receive the following error message after the command **npm start** (as admin):
I'll checked, unfortunately lots of folder in the **node_moduls** folder but no **npm** folder

Error: Cannot find module 'C:\Users\JH\Desktop\MIQ\miq-nz-booking-tools-master\miq-nz-booking-tools-master\MIQ-Booking-Assistance\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\JH\Desktop\MIQ\miq-nz-booking-tools-master\miq-nz-booking-tools-master\MIQ-Booking-Assistance\node_modules\npm\bin\npm-cli.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

Thanks for your help

**Comment by jvolker** [comment]
Normally, when you have Node.js installed, NPM gets installed as part of that too. You don't need to see an npm package in the node_modules folder as it's installed globally and you can call it from any directory/folder.

What directory do you start `npm start` from? It should be `miq-nz-booking-tools-master\MIQ-Booking-Assistance\`.

**Comment by Joeheim** [comment]
Yes, starting it from miq-nz-booking-tools-master\MIQ-Booking-Assistance\.

Error message stays the same. Deleted everything, reinstalled... problem persists

:-(
![Screenshot (2)](https://user-images.githubusercontent.com/87252944/125255757-df1be180-e34f-11eb-9bf9-c9ab0bedd5f2.png)

**Comment by alexDrinkwater** [comment]
@Joeheim Have you run `npm i` in the MIQ-Booking-Assistance folder/directory?

**Comment by Joeheim** [comment]
@alexDrinkwater  Yes

**Comment by jvolker** [comment]
My feeling is this has nothing to do with these scripts.

Googling "cannot find module npm-cli.js" pointed me to https://stackoverflow.com/questions/24721903/npm-npm-cli-js-not-found-when-running-npm. Hopefully, one of the suggestions in there will help you.

It sounds like your Node.js installation might be corrupt. I could imagine reinstalling might help.

**Comment by jvolker** [comment]
You might like to give the binary release a try which we just released (big thanks to @alexDrinkwater): https://github.com/jvolker/miq-nz-booking-tools/releases/latest You don't need to code for that.

Feel free to reopen if you have more questions.

**Comment by Joeheim** [comment]
Sorry for the late response.

New Version works excellent.

Thanks
