### ISSUE TITLE
New script not working?

### ISSUE THREAD

**Issue by Saj22** [jvolker/miq-nz-booking-tools#103]
Hi guys

I have been running the new script (10.3).  I got an alert from MIQ4U an availability in September but no alert came up on the script.

Previously I would get the MIQ4U alert a few seconds after the alert on the script.  

Anyone else experiencing alert from elsewhere but not on the script?

Really appreciate all the work you are doing on this!

**Comment by Saj22** [comment]
I will keep running the script and monitor against updates from MIQ4U....if anything changes I will let you know.

**Comment by mark-bloom** [comment]
I'm getting available dates appearing occasionally. No success on reserving any yet, so my question would be more "does the new date selection method actually pass through correctly?"

**Comment by Saj22** [comment]
I just received my first alert,   So script is working.  But I have also not had no success on securing any allocation.  I will update if I notice anything else.

**Comment by mark-bloom** [comment]
I did notice the "this date is now full" error is appearing, so implication is that it's all working/submitting fine. But once someone using the script has success, we'll know better.
