### ISSUE TITLE
Not sure if “next” button working in v10.3?

### ISSUE THREAD

**Issue by JulieONeill** [jvolker/miq-nz-booking-tools#105]
First off - thank you SO MUCH for providing and updating this assistance.

I’m on Windows and have downloaded the script v10.3. I have two problems and this post is about the first of them: whether the “next” button is working.

I’ve heard the alert a few times and ticked the “not robot” button then tried clicking next but it hasn’t seemed to respond - i.e., no visual movement of the button and no “in progress” swirling circle. It was doing both in v10.2 

Is this normal or an issue?

Thank you!

**Comment by Saj22** [comment]
I am experiencing the same thing with the next button.  Doesn't take me anywhere.  I don't get anything in progress and when I click to restart get the recaptcha error message and have to log out and back in.   Earlier, when the script was not working and I was doing it manually, I saw the please wait - in progress - this room is now full.  It is the first time I have seen that in a long time.  When using the script I only get the recaptcha error message and have to log out and back in when unsuccessful (ony after clicking next).  If it is just the siren then no problem restarting.   But I guess there is no way to tell if it is working unless someone can get an actual booking and confirm.  It's been a frustrating couple of weeks.  This whole MIQ system is cruel and illogical.

**Comment by JulieONeill** [comment]
I got a voucher (twice) using the v10.2 script (though sadly they were both for days without corresponding flights out of my country of departure). And with v10.2, I could click “next” and the button visually looked ‘clicked on’ and a moving/swirling circle appeared - sometimes it would then just stay on the same page (I guess if I had been too slow); sometimes take me to a “sorry, full” page and - twice - to a “voucher reserved” page. But with v10.3 I’m not sure if the “next” button is working as it’s not responding the same way (and even when the alert is still going off, it doesn’t seem to respond to me clicking it).

Definitely a painful process - grateful for this community’s help with it!

**Comment by Saj22** [comment]
Great to hear you were successful in getting vouchers. Hopefully with this
version we can all get there!

**Comment by mark-bloom** [comment]
Mmm, I was also previously successful with v10.2 (but it was for a Sunday, which... I cannot get to Japan or China to then get to NZ). Let's keep hoping with v10.3 that we'll all make it!

**Comment by alexDrinkwater** [comment]
If you see this issue again can you try re-clicking on the date in the calendar again before clicking next

**Comment by JulieONeill** [comment]
Thanks @alexDrinkwater 
One request on this (that someone else mentioned in another issue/comment thread): the Windows v10.3 script’s page refresh scrolls to the bottom of the page which, on my laptop, means I can’t see the calendar and have to take a second to scroll up when I hear the alert. Is there a way to make it refresh and set back to the portion of the page where the calendar is visible?
Thank you for all you’re doing!!

**Comment by nikhil-bhandari** [comment]
The issue with Next button is because of the website. It sends a XHR request to check duplicate bookings but it does not disable the button or display a spinner.

**Comment by alexDrinkwater** [comment]
@nikhil-bhandari Thanks for the info. TBH, I've spotted a few bugs in the latest code from MIQ. Seems like they also no longer send the date with the check duplicate XHR request and it also looks like it does not come in the form data on the form submit after check duplicates. Looks pretty sloppy to me. I guess the include it in the date in the form token?

**Comment by JulieONeill** [comment]
@nikhil-bhandari @alexDrinkwater Do your comments above mean the script is working and we should keep: listening for alert, clicking on the date that has come available, clicking “not robot”, clicking “next”?
I just tried this and had no luck getting the page to respond to me again (neither the date nor the next button looked clicked upon and no “in progress” type visual appeared)

**Comment by alexDrinkwater** [comment]
@JulieONeill Based on @nikhil-bhandari comments it sounds like the latest miq site doesnt give any feedback to say the page is loading or the button has been clicked. After a few seconds does the page 'refresh'?

**Comment by JulieONeill** [comment]
@alexDrinkwater Thanks for clarifying! No, once I’ve clicked the page (on the date / not-robot / next buttons), that seems to stop the script running - and the MIQ site also seems to then log me out after a few moments (after clicking once hearing an alert… which I mentioned in a different issue/comment post - #106).
Thank you all again for continuing to help with this!

**Comment by JulieONeill** [comment]
@alexDrinkwater @nikhil-bhandari To further  clarify the above - should I still try to click the date that becomes available before the “not robot” and “next”? I’ve tried it both ways (clicking date first; going straight to robot/next) and am not having any luck so can’t tell which way is actually working

**Comment by alexgcnz** [comment]
@JulieONeill I'm also having the same issue: alarm sounds, click on the date, check "I'm not a robot", click "Next" .... nothing happens. Not sure if this due to the script, or something to do with the MIQ site. Am also experiencing the other issue #106

**Comment by JulieONeill** [comment]
I’ve had no success with the page responding to my clicks after any alerts so I tried creating a second MIQ login to have one booking window open without the script and another window open with the script so that I could hear the alert from the script window, click manual refresh on the non-script window and then click date/not-robot/next on the non-script window… BUT weirdly the non-script window wasn’t showing any available dates even when the script window had the alert sounding. Not sure if this signals an issue with MIQ or script…?

**Comment by kimmered1234** [comment]
> I’ve had no success with the page responding to my clicks after any alerts so I tried creating a second MIQ login to have one booking window open without the script and another window open with the script so that I could hear the alert from the script window, click manual refresh on the non-script window and then click date/not-robot/next on the non-script window… BUT weirdly the non-script window wasn’t showing any available dates even when the script window had the alert sounding. Not sure if this signals an issue with MIQ or script…?

Hi Julie.. how did you have two windows open at the same time?  I thought it would log you out if you were logged in twice?

**Comment by Saj22** [comment]
Hi Julie

I am trying the same thing now.  Will keep you updated if I find the
same....

**Comment by Saj22** [comment]
I have one window open for my partner with the script running and one for
myself without the script.  Will see how that goes.

**Comment by mark-bloom** [comment]
@kimmered1234 as mentioned, they have multiple accounts running with (probably) the same passenger details.

Regarding the inability to reserve a date, it seems that with the new website changes, it might have begun possible to do headless scripting, so there might be some scripts doing instant submission out there.

**Comment by JulieONeill** [comment]
@mark-bloom Yes that’s what I was trying (created two MIQ logins with same passenger details). I’m sadly not tech-literate enough to know what the “headless scripting” etc stuff means - but do you think, when running the v10.3 script & hear the alert, we should be clicking the date before “not-robot” & “next”, or go straight to clicking the “not-robot” & “next”? (The “next” button becomes active as soon as the alert goes off but it doesn’t seem to visually respond to anything). I’ve tried both ways but no success with either - the page doesn’t do anything to make me feel it’s “heard” my clicks.

**Comment by JulieONeill** [comment]
Based on the example of success shared in the “help wanted” comment thread, it seems that it is not necessary to click the date and sufficient to just click the “not robot” and “next” buttons so I will close this issue

**Comment by stilljake** [comment]
> @kimmered1234 as mentioned, they have multiple accounts running with (probably) the same passenger details.
> 
> Regarding the inability to reserve a date, it seems that with the new website changes, it might have begun possible to do 
headless scripting, so there might be some scripts doing instant submission out there.

It was always possible to do headless scripting, I have a solution I wrote that can refresh every second, select date, click captcha and click next (I plan to share it too but it is cli only and not very user friendly right now). Funnily enough even with that, I have still never been fast enough to get a date. It takes me to the "holding your date screen" 99% of the time and then I get a "date is full message". If I check my logs I can see how long a date was available and it is usually less than 1 second. My assumption is there are plenty of other bots doing the same thing, and probably most of them closer to the MIQ servers in Sydney so have less latency (I am in EU).

**Comment by mark-bloom** [comment]
@stilljake Good to know that it's possible. Even with my attempts at headless, I haven't been able to bypass the time-out that seems to happen at <5s refresh times.

**Comment by stilljake** [comment]
@mark-bloom by timeout do you mean the soft ban for making too many requests too fast?

**Comment by mark-bloom** [comment]
@stilljake Yeah, that's the one. Anything under 5 seconds (even 4.7) seems to reach some threshold of 'requests per 5 minutes' or something I haven't bothered diagnosing.

**Comment by stilljake** [comment]
My solution was to use a proxy and rotating my IP every refresh.
