### ISSUE TITLE
Does VPN compromise speed of script?

### ISSUE THREAD

**Issue by JulieONeill** [jvolker/miq-nz-booking-tools#115]
I’m using version 10.3 on Windows. I have to use VPN for my work. Does using VPN compromise the speed of the script?
Thanks for any guidance – I am not very tech savvy!

**Comment by stilljake** [comment]
It might. It depends where your VPN server is located and if it is routing all your traffic through it, or just pushing specific routes (to access your companies services). A VPN also encrypts/decrypts all your traffic, which is great for security and privacy, but the tradeoff for that it takes time. However in some cases a VPN could potentially increase the speed by taking your traffic via a more efficient route to the target.

**Comment by JulieONeill** [comment]
@stilljake Thank you!! I’ll close this issue/question
