### ISSUE TITLE
help a newbie out - guide for dummies (please!)

### ISSUE THREAD

**Issue by natashajtk** [jvolker/miq-nz-booking-tools#16]
Hi, I'm trying to install the MIQ Booking assistance script (with no experience in coding). Can anyone share a bit more guidance for dummies like me... Would be massively appreciated, I'm lost at the install npm-i. Thanks!

**Comment by yizeng** [comment]
@natashajtk

1. What's your operating system?
2. Do you have [Node.js](https://nodejs.org/en/download/) installed properly? Check via `npm -v` in a command prompt/terminal. It should be something like `6.14.13` (or some other number)
2. Did you navigate to the MIQ-Booking-Assistance folder correctly? Check via `pwd` in the terminal.

**Comment by jvolker** [comment]
Just slightly changing the subject of this post as I think this issue has nothing to do with your gender if anything your experience in coding.

That said, the people working on this project aim to make this easier for people with little or no coding skills. So you are more than welcome to ask for help here. As @yizeng already pointed out, you need to be more specific for others to be able to help you, though.

**Comment by natashajtk** [comment]
Hi both, thanks for replying and updating the post title. 

I am running Windows 10, but also have a Mac if that would be easier... 
![2](https://user-images.githubusercontent.com/87370276/125621435-d7ac0789-bd3f-4015-8583-bc747383ef94.JPG)
![3](https://user-images.githubusercontent.com/87370276/125621439-d01a3c57-6b83-4a9a-84b5-61f782f3ac9c.JPG)
Installed Node.js with Windows 10 option, uninstalled and reinstalled, still not coming up if i type into the command prompt/terminal. (screen shot attached below).

Can't get it to navigate to the MIQ folder, am I doing this correctly (probably not, hah!) screen shot below...

thanks 八(＾□＾*)

**Comment by yizeng** [comment]
@natashajtk Okay, looks like you're almost there.

You'll need to go into the directory first (in your screenshot 1, your current directory was `C:\Users\Computer`).

Type in this command in your command prompt: `cd C:\Users\Computer\Downloads\miq-nz-booking-tools-master\MIQ-Booking-Assistance`

Then check `npm -v` (note it's npm space hyphen v, best just to copy and paste) to make sure your NodeJs is installed correctly.

Then use `npm i` to install the dependencies as suggested in the README.

If there's no error shown, use `npm start` to continue.

**Comment by natashajtk** [comment]
@yizeng  Thanks for your reply!! 

When I open it up the directory seems to be stuck as "C:\Users\Computer>" I can't delete this to start fresh with anything else.... (as in screenshot below), is there a way to change this? thanks!!

![4](https://user-images.githubusercontent.com/87370276/125631582-7ef51199-1076-49a0-af1c-09b5f72cb2c6.JPG)

**Comment by yizeng** [comment]
@natashajtk You should be able to type in (or paste in): `cd C:\Users\Computer\Downloads\miq-nz-booking-tools-master\MIQ-Booking-Assistance`.

`cd` here means "Change Directory", so you'll be in the correct folder.

If not, press `Ctrl` and `D` on keyboard at the same time first. Then try paste again

**Comment by natashajtk** [comment]
@yizeng YOU ARE A SUPERSTAR - IT WORKS!! Honestly thank you so much for getting me this far. 

It's just searching for the default at the moment (not sure which month, I think Nov as it scrolls across to that each refresh), I saw there is the option to change as below, but when I try and open the file it comes up with the below error... 

"These defaults can be changed at the top of the file index.js under MIQ-Booking-Assistance folder. Customization is limited to those options at this stage but can be achieved by extending the script."


![5](https://user-images.githubusercontent.com/87370276/125636671-e9de9b75-5a31-4c6b-b9cb-b0773140a68b.JPG)

**Comment by yizeng** [comment]
@natashajtk Yeah that's just the stupid Windows thing that you can ignore.
Right-click the file and choose to open with a text editor, for example, notepad.
Then you'll see Line 5 as `const month = 11;`, which means the default is November. Change the number to the month of your choice, e.g. 9 means September.
Save the file and re run the `npm start`

**Comment by natashajtk** [comment]
@yizeng - amazing! Really appreciate the guidance, fingers crossed I can get a spot!

**Comment by yizeng** [comment]
@natashajtk No worries! Good luck! After all this time, I haven't even got myself a spot yet. 😭

**Comment by natashajtk** [comment]
Noooooooooo I hope you get one soon!

**Comment by jvolker** [comment]
Closing this as the issue seems resolved. Feel free to reopen in case you are still running into issues.

**Comment by natashajtk** [comment]
Thanks!
