### ISSUE TITLE
MIQ Booking Assistance Month Select Query

### ISSUE THREAD

**Issue by SMIRCH** [jvolker/miq-nz-booking-tools#19]
Hi, firstly thanks for all of your great work with this.  I've yet to get a spot, but your work gives me some hope...

With the updated code, should we just be updating the required month on line 5, or should we also be selecting the same date on line 91?
e.g
Line 5 - const month = 8;
Line 91 - fp.changeMonth(month - 8, false)

**Comment by royce87** [comment]
only line 5

**Comment by yizeng** [comment]
Changing Line 5 should be enough. For example, changing 8 to 11 will select November.

**Comment by jvolker** [comment]
Closing this issue now as it seems solved. Feel free to reopen it if necessary.
