### ISSUE TITLE
Twin Rooms

### ISSUE THREAD

**Issue by gizelle6** [jvolker/miq-nz-booking-tools#20]
Thanks heaps to Jeremias for developing this and all the others who are continuing to develop it. I am a newbie but with a bit of help, have it working. There is a suggestion somewhere that the hardcode double room can be changed to twin. Where and how do I do that?

**Comment by yizeng** [comment]
@gizelle6 I don't think the double room option is hardcoded in the code (it only has the disability question (aka `accessibilityRequirement`)).

If you have some Javascript skills, you can try to add these in:

```
const roomType = 'Twin share'; // add this after Line 5
```

```
page.$eval('#form_rooms_0_room', (el, roomType) => { el.value = roomType }, roomType) // add this after Line 84
```

**Comment by jvolker** [comment]
As @yizeng  said. It's not in there yet, but [this pull request](https://github.com/jvolker/miq-nz-booking-tools/pull/14) includes it and looks very promising. I will try to merge it asap.

**Comment by alexDrinkwater** [comment]
@gizelle6 This is now implemented

**Comment by jvolker** [comment]
You might like to give the binary release a try which we just released (big thanks to @alexDrinkwater): https://github.com/jvolker/miq-nz-booking-tools/releases/latest You don't need to code for that.

Feel free to reopen if you have more questions.

**Comment by gizelle6** [comment]
Jeremias

 

Great work. My only question relates to the alarm. How do you restart after refreshing to turn off the alarm. I have been exiting the programme and then restarting the exe & logging in again. It works but I might be missing a shortcut.

 

Cheers

 

Murray

**Comment by jvolker** [comment]
I think it should be possible pressing CTRL + R (on Windows) or CMD + R (on Mac).
