### ISSUE TITLE
doesnt show any available dates now..

### ISSUE THREAD

**Issue by nz-matt** [jvolker/miq-nz-booking-tools#23]
showed a few dates that i couldnt get, now 24hrs of nothing at all, no beep..
maybe server notices and blocks me now by sending booked 24/7

**Comment by jvolker** [comment]
This sounds like very normal behaviour considering the demand at the moment. 

> maybe server notices and blocks me now by sending booked 24/7

I have not heard of this behaviour before, although it could be possible. I assume it's probably just full.

I'm going to close this for now. But please report back on this issue if alerts are coming up for you again or you don't receive them anymore.
