### ISSUE TITLE
help

### ISSUE THREAD

**Issue by pkeenan1** [jvolker/miq-nz-booking-tools#24]
new to coding, on a mac starting from scratch any suggestions?? so far downloaded the terminal and already stuck

**Comment by jvolker** [comment]
You need to be more specific. 
- What part of this project did you use? 
- What is your specific question? 
- What do you expect and what do you see instead?

**Comment by jvolker** [comment]
You might like to give the binary release a try which we just released: https://github.com/jvolker/miq-nz-booking-tools/releases/latest You don't need to code for that.

Feel free to reopen if you have more questions.

**Comment by pkeenan1** [comment]
thank you so much for your help!!
