### ISSUE TITLE
Possible bug: keeps refreshing after date selection

### ISSUE THREAD

**Issue by jvolker** [jvolker/miq-nz-booking-tools#28]
Posted in #25 by @sankeerthgone

> HI , after date selection is any possibility to avoid page refreshing , after date selection and filling captcha its refreshing and coming to start again

@alexDrinkwater do you have a recommendation on how to debug/test this? It seems free spots and therefore alerts are rarer these days. Can we mimic it somehow?

**Comment by alexDrinkwater** [comment]
@jvolker I am thinking we need to add automated unit testing. I've been looking into it but we may want to change the class on a date to simulate a date being available.

**Comment by jvolker** [comment]
Yes, this sounds like a great idea. I don't have a lot of knowledge about testing though. Would you be able to set up a test environment and that particular unit test?

**Comment by alexDrinkwater** [comment]
@jvolker I just changed line 115 to `var available = document.querySelectorAll('.flatpickr-day.flatpickr-disabled');` and the beep is working fine for me and I don't see any refreshing after a date is found...

**Comment by alexDrinkwater** [comment]
@jvolker I'm not able to reproduce this issue on the book assistance. Maybe it was for the chrome extension?

**Comment by jvolker** [comment]
> @jvolker I'm not able to reproduce this issue on the book assistance. 

Thanks for checking @alexDrinkwater. I guess that's a good thing. :) 

> Maybe it was for the chrome extension?

@sankeerthgone could you please confirm what part of the software you were using - MIQ Booking Assistance (Node.js script) or MIQ Alert (Chrome browser extension)?

**Comment by alexDrinkwater** [comment]
Unable to reproduce.
