### ISSUE TITLE
Stuck after downloading Node

### ISSUE THREAD

**Issue by ramajama1990** [jvolker/miq-nz-booking-tools#29]
Hi all,

I've got no coding experience or anything like that. Thought I could follow the instructions but stuck after downloading node.

I downloaded node on windows, followed the install wizard let it do its thing.

Number 2. on the instructions 'Open a command-line window and navigate to the MIQ-Booking-Assistance folder and run npm i to install all dependencies'.

How do I open a command-line? I tried opening node and typing MIQ-Booking-Assistance and it didn't work, I typed MIQ-Booking-Assistance in the node command prompt window that was also in the downloaded files and that didn't work either. I've tried to read through the help and other files and I feel like I'm missing something big and obvious here.

Would love some help if someone has time for someone who doesn't know whats going on.

Cheers!

**Comment by jvolker** [comment]
I'm not sure what operating system you are on. A command-line window is called "Terminal" on macOS and "Command Prompt" on Windows. "node command prompt" sounds like what is a command-line window. So you are probably in the right place.

Instead, you might like to give the binary release a try which we just released: https://github.com/jvolker/miq-nz-booking-tools/releases/latest 
You don't need to code for that.

Feel free to reopen if you have more questions.
