### ISSUE TITLE
Running on M1 OSX issue...

### ISSUE THREAD

**Issue by HughAndersonNUS** [jvolker/miq-nz-booking-tools#3]
Hi,
First - thanks for a useful tool - I hope it helps me get a spot.
It works fine for me in a linux VM, but trying to run it natively on an Apple M1 (armv6) based processor has issues with accessing chromium (which is at /opt/homebrew/bin/chromium). The build completes, after setting these:
```
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
PUPPETEER_EXECUTABLE_PATH=/opt/homebrew/bin/chromium
```
However, when trying to run MIQ-Booking-Assistance, it does this:
 
```
hugh@adminsocs-mbp MIQ-Booking-Assistance % npm start
> miq-nz-booking-tools@1.0.0 start
> node index.js
/Users/hugh/Downloads/miq-nz-booking-tools-master/MIQ-Booking-Assistance/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193
            reject(new Error([
                   ^
Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT

```
I then tried to set the browser using the launch script:
```
    const browser = await puppeteer.launch({ 
        executablePath: '/opt/homebrew/bin/chromium',
        ......
```
But this made no difference. Do you have any suggestions as to how to make the script recognize the chromium browser?
Cheers Hugh

**Comment by HughAndersonNUS** [comment]
Hi - I have an awful fix. But I'll just put it in here.
After setting the environment variables to build, I then went into the sources under `node_modules`, and changed all occurrences of `/usr/bin/chromium-browser` to `/opt/homebrew/bin/chromium`.
And then it worked.
Cheers Hugh

**Comment by cjyprice** [comment]
Hey! I just tried the new release on my M1 MacBook Air and it's working. I just had to go to security settings and select open anyway because there was security alert. But after that it was all good!

**Comment by jvolker** [comment]
Thanks a lot, @cjyprice for testing this and giving feedback here.

Closing this for now.
