### ISSUE TITLE
Advantage to NZ users

### ISSUE THREAD

**Issue by alexDrinkwater** [jvolker/miq-nz-booking-tools#38]
As more people are using "scripts" one thing to highlight is the advantage New Zealand users have over foreign users. This is because it takes longer for people with a higher latency between their device and the servers in wellington (or wherever they are in NZ) to send the request for a room. If you have access to a computer physically in New Zealand it will be at an advantage to find spots over one further away.  This reminds me of how the NYSE has 38 miles of extra wire for connections that are in the building to increase their latency and reduce the time advantage they have for trades. This maybe something to add to the documentation.

**Comment by MannerlyApple94** [comment]
I believe I first read about this in Flashboys, a great read on the topic!
