### ISSUE TITLE
was not able to confirm booking after clicking next went to confirm accommodation not sure why

### ISSUE THREAD

**Issue by nedmi** [jvolker/miq-nz-booking-tools#40]
when I responded to  the beep immediately for a  available room i completed the re-CAPTHA and hit next 
I went to enter your accommodation screen it happened 2 time for same room within 5 minutes 
did i just miss the mroom because someone was faster or what else could it be? I felt like i had been able to move right trough within 2/3 second to secure the 2nd time i as able to secure

**Comment by alexDrinkwater** [comment]
@nedmi As noted in the other issues, its a race against thousands of others.
