### ISSUE TITLE
Booking 2 Rooms 

### ISSUE THREAD

**Issue by jambla9** [jvolker/miq-nz-booking-tools#41]
Thanks Mr Volker. This is great! 

However, I'm hoping to book 2 rooms for a family of 5. Is there any way of adding a pre-filled tick 'No' for the disability needs question for room 2 as well?

**Comment by jvolker** [comment]
There has been some work done on this in #2, but it's not merged yet. It would be good to implement it into the app.

**Comment by jambla9** [comment]
Thank you for the update.

Will you be updating again now that the MIQ registration page has changed
this morning?

**Comment by alexDrinkwater** [comment]
fixed in #48 because the MIQ page now gets you to specify your room requirement on a separate step before selecting the date.
