### ISSUE TITLE
not confirming the date after hitting next on callendar page

### ISSUE THREAD

**Issue by nedmi** [jvolker/miq-nz-booking-tools#42]
HI I got the beeped I again the 3rd time,I pushed in-captcha then next button went to  the next screen said confirm accommodation the next step did not complete , the messages I have seen before  once to hit next after picking an available date is something like"wait while your booking is confirmed"  however it just went  backwards to confirm accommodation I think there may be a bug in it as it  that makes it go backwards to the page that is  already auto filled? any suggestions on what to do? also all 3 beeps were on November 1st

**Comment by alexDrinkwater** [comment]
@nedmi The behavior that you describe is common among people that are not using this tool/script as well. There are thousands of people all refreshing the page at once. It only takes one person that a few milliseconds before you for you to not get the spot. Sorry you are having a hard time.

**Comment by nedmi** [comment]
THanks Alex I thought that was the answer I will plug away all good (:-)
what about setting specific dates I do not have that feature?
cheers
