### ISSUE TITLE
Should script scroll through months on screen?

### ISSUE THREAD

**Issue by kz10111** [jvolker/miq-nz-booking-tools#43]
Just checking if script is working correctly for me - I've selected 'any date' however on secure allocation page only see July on screen and does not scroll to other months.  Is this correct?

**Comment by jvolker** [comment]
I can confirm that the app isn't scrolling for me either. I'm not sure, but I think it would have to do that to detect free spots. 

@alexDrinkwater, what do you think?

**Comment by alexDrinkwater** [comment]
@kz10111 That is the correct behavior as of 0.10.0

@jvolker The new way of detecting spots across multiple months doesn't need to scroll across months. Instead we use the "data-arrival-dates" attribute which contains a underscore separated list of dates e.g. "2021-10-10_2021-7-8". This attribute is what the miq source code uses to enable certain dates across all the flatpickr months. This is an excerpt from the miq source code: 
```
this.calendarElement.getAttribute("data-arrival-dates").length > 0 ? this.calendarElement.getAttribute("data-arrival-dates").split("_").sort() : []
```
 and this is the function/data they provide to the flatpickr "enable" property in the flatpickr config:

```
enable: this.availableDates.length > 0 ? this.availableDates : [function() { return !1 }
```

I found this by unminifying the miq source code
