### ISSUE TITLE
MIQ Assistance Download error message: Mac version won't open because the developer can not be verified 

### ISSUE THREAD

**Issue by cjw207** [jvolker/miq-nz-booking-tools#46]

**Comment by alexDrinkwater** [comment]
@cjw207 This is expected. It costs $500 to get a certificate for the application to be "verified", as this is a volunteer run project we won't be certifying it. Here is how to bypass this message to open the app: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by cjw207** [comment]
Thank you so much @alexDrinkwater
