### ISSUE TITLE
Room type selection now separated from date selection

### ISSUE THREAD

**Issue by gizelle6** [jvolker/miq-nz-booking-tools#47]
The MBIE booking system has been amended so that you select and save the room requirements and then move to Arrival Details (room selection)  in a separate window.

**Comment by VenusNg** [comment]
Is it this change/reason so I can't run the code program now?

**Comment by Anwere** [comment]
I seem to be having same issue... It was running and then just stopped, presumably after that change.

Can't seem to get it to run again either

**Comment by hiltmacc** [comment]
Hi @alexDrinkwater I have the MIQ NZ Booking Assistance app on mac, sorry are you able to let me us know how to update it to fix with the new changes to the MIQ site? Many thanks for your help!

**Comment by alexDrinkwater** [comment]
I've uploaded the new windows version, you will need to wait for @jvolker to upload the mac version.
