### ISSUE TITLE
Mac version 0.10.0

### ISSUE THREAD

**Issue by Deroles** [jvolker/miq-nz-booking-tools#50]
Hi There

Just downloaded MIQ Booking assistance v 0.10.0 for Mac and followed instructions.
The App has fired up Chromium and I have logged in and navigated to the select date page.
App says: **Found "Secure your allocation" page! Wait for beep sound, then select date and continue bookin**g.
Browsers says it is being controlled by automated test software.  But the page is not being refreshed every 5 seconds as the App window indicates.   App window Restart Search button is also grayed out.
The MIQ site then times out and asks for re-login.

**Comment by Deroles** [comment]
mac OS 10.15.7

**Comment by alexDrinkwater** [comment]
@Deroles 0.10.0 has known issues with the current miq site.
