### ISSUE TITLE
Windows v0.10.1 reCAPTURE

### ISSUE THREAD

**Issue by Anwere** [jvolker/miq-nz-booking-tools#52]
Hi there,

I had an earlier issue of the app not refreshing however I've run the new 0.10.1 version and that seems to have fixed it so thanks for that.

Quick question though, does it make any difference or if the reCAPTURE "I'm not a robot" box is checked or not? Or is the script automating that?

Thanks

**Comment by alexDrinkwater** [comment]
@Anwere The recapture still needs to be clicked otherwise you will get an "invalid Recapcha" error and when you click next after a date becomes available it will not reserve your spot.

**Comment by Anwere** [comment]
@alexDrinkwater thanks, just so I'm understanding correctly though (sorry, full pleb here) I need to re-check it each time it refreshes? I had it running earlier but wasn't getting any "invalid Recapcha" error plus unless I extend the default 5 second time not much window to do so either

**Comment by alexDrinkwater** [comment]
@Anwere No you just need to do the recapture once you start hearing the beep noise (make sure your speakers volume is not muted) and the message "AVAILABLE! ..." message appears in the small window with the settings..

**Comment by Anwere** [comment]
@alexDrinkwater thanks, sorry it was a dumb question with hindsight... Lot of stress at the minute!
