### ISSUE TITLE
Updated MIQ page format?

### ISSUE THREAD

**Issue by Ferdi9445** [jvolker/miq-nz-booking-tools#53]
Hi there,
It seems like MIQ have updated their site format, likely to force all current scripts to be updated.
They now have a a) and b) section for booking a room / date. See the attached screenshot.
Cheers,
Ferdinand
![image](https://user-images.githubusercontent.com/87695207/126286095-3c428ac5-5c41-42c0-91a1-ad7fbca91387.png)

**Comment by michaelzero00** [comment]
I believe the new site structure is addressed in the new code released three hours ago. But I have found a new issue: https://github.com/jvolker/miq-nz-booking-tools/issues/54#issue-948447056

**Comment by alexDrinkwater** [comment]
@fixed in #54
