### ISSUE TITLE
Mac software update?

### ISSUE THREAD

**Issue by jdobbsy** [jvolker/miq-nz-booking-tools#56]
Hi there, I was just wondering whether there'll be an update for Mac users too, now that the MIQ website has changed? Cheers :)

**Comment by ghost** [comment]
Yes, wondering this too, patiently rechecking thinking its in progress ;)

**Comment by alexDrinkwater** [comment]
@jvolker Do you have time to make a new mac build for 0.10.1 please?

**Comment by marak210** [comment]
The latest version of Windows seems to be missing the month selection too

**Comment by alexDrinkwater** [comment]
@marak210 can you post a screenshot of what you mean? Did you try selecting 'no' for find any date?

**Comment by jdobbsy** [comment]
Thank you so much @alexDrinkwater @jvolker :)

**Comment by jdobbsy** [comment]
@alexDrinkwater @jvolker Hey guys, I've just downloaded the new Mac version but sadly it doesn't refresh the page. Is there any way to fix this? Cheers :)

**Comment by jvolker** [comment]
Sorry, I didn't get to it earlier. I've just uploaded the new version: https://github.com/jvolker/miq-nz-booking-tools/releases/latest

**Comment by hiltmacc** [comment]
@jvolker thanks mate, quick query, when I enter a month I can't seem to restart the search, it's greyed out and the page just refreshes july. Any thoughts on why? Many many thanks for all your help to everyone
<img width="1673" alt="Screenshot 2021-07-20 at 2 08 36 PM" src="https://user-images.githubusercontent.com/87687173/126381791-ddf42a98-6af1-4841-b357-5b7dbe9fd161.png">

**Comment by alexDrinkwater** [comment]
@hiltmacc You don't need to restart the search. The restart search button only is enabled when a date is found and you want to restart because you missed out on it or didnt want that date. It picks it up as soon as you add it. Don't worry that you don't see the month change. It checks the month in the background without switching.

**Comment by hiltmacc** [comment]
@alexDrinkwater ah ok thanks Alex, much appreciated! :)

**Comment by Ghadanz** [comment]
Thank you Alex so much.
