### ISSUE TITLE
Could the system please reset when we don't manage to get the date in time?

### ISSUE THREAD

**Issue by michaelzero00** [jvolker/miq-nz-booking-tools#58]
As of writing, I've never been able to secure a date in time. So the page refreshes instead of going to the next step. But it seems that because "found" has been triggered, the proggy stops work. 

It would be great if it could detect the page has simply refreshed and not gone on to the next steps of the booking.

Thanks so much for working on this project.

**Comment by alexDrinkwater** [comment]
@michaelzero00 I believe the "Restart Search" button in the electron application does what you describe. If you are after the same functionality by using the script via node I would be happy to review a PR you submit.

**Comment by annehulsey** [comment]
@alexDrinkwater After I click "restart seach", the browser says "Invalid reCAPTCHA - please try again" over the reCAPTCHA box. I can't get it to go away without closing and reopening the .exe file. Is this message innocuous or do I need to reopen the .exe every time?

**Comment by alexDrinkwater** [comment]
@annehulsey I believe it is innocuous however it does come up because your reCaptcha was invalid for some reason before clicking next. Make sure the reCaptcha doesn't give you an error before clicking next. I'm not sure of a way to remove the error without exiting the program at the moment. You could try navigating away from the calendar page.

**Comment by annehulsey** [comment]
Thanks, @alexDrinkwater. If I go all the way back to home, it removes the error.

That said, about half the time I still have the issue with the reCaptcha. Every time, I get the green check before hitting next. If the page refreshes and includes a message bar saying "The date is now full. Please try another date", then the "Restart Search" does not result in the Invalid reCaptcha message. However, if the page refreshes without securing the date but does NOT include the "date full" message, hitting "Restart Search" gives the Invalid reCaptcha message.

I provided these details on the off chance that they are helpful. But I'm guessing that this is more an issue with the MIQ system than with your code's interaction with it.

**Comment by alexDrinkwater** [comment]
I believe @michaelzero00 issue is handled with the reset button.
