### ISSUE TITLE
Having trouble getting the updated Mac script to search for the right month. Help?

### ISSUE THREAD

**Issue by regaltic** [jvolker/miq-nz-booking-tools#59]
Was no issue in the previous script, but unsure which values to change and in what form. If somebody could advise, would be much appreciated. 
Thanks

**Comment by jvolker** [comment]
Please try the latest release 0.10.1 for Mac: https://github.com/jvolker/miq-nz-booking-tools/releases/latest

**Comment by regaltic** [comment]
thank you @jvolker !

**Comment by jvolker** [comment]
You're welcome. Please close this issue if it worked.
