### ISSUE TITLE
Alerts not working

### ISSUE THREAD

**Issue by tysonandone** [jvolker/miq-nz-booking-tools#60]
Hello and thank you so much for putting this together to help folks like me get an MIQ booking! Also, sorry for bothering you with this issue.

I'm on v0.10.1 (windows) and have added a number of dates (see screenshot) and one became available (18 Nov) but I didn't receive an alert (I also receive alerts from the Twitter bot, so that's how I know that the date became available). Any ideas? Thanking you in advance!

![image](https://user-images.githubusercontent.com/87716917/126363989-fb4e66cd-eeb7-4408-87e6-93b2492b731f.png)

**Comment by alexDrinkwater** [comment]
@tysonandone It seems like the application is in a strange state. It shouldn't say "starting" at the top once has been refreshing the page. If you restart the application does it remain on "starting"?

**Comment by tysonandone** [comment]
@alexDrinkwater thanks for your response. I've restarted and this is the new state.

![image](https://user-images.githubusercontent.com/87716917/126372350-f0919c18-cdb4-44a0-bed2-41188fa6a9db.png)

**Comment by alexDrinkwater** [comment]
@tysonandone That looks better, let me know if it doesn't alert you now. Sorry about the spot you potentially missed out on.

**Comment by tysonandone** [comment]
@alexDrinkwater thank you very much and don't be sorry!
