### ISSUE TITLE
version 10.0 loaded it is not cycling from July or checking for available date 

### ISSUE THREAD

**Issue by nedmi** [jvolker/miq-nz-booking-tools#61]
Hi Alex and Jeremias i, thanks loads for the chance to get a spot 
I loaded 10.0  it just sits on current month (July ) the program after i complete the log in into the miq to secure a room.
I do not see it screening at all..
i followed the instructions, do you have any suggestions to get it to reset and run?
thanks Nedmi

**Comment by annehulsey** [comment]
I believe this is expected behavior. Mine also only shows July during the search but still found a spot in August.

**Comment by alexDrinkwater** [comment]
@nedmi Firstly, make sure you are on 0.10.1, 0.10.0 no longer works after MIQ site updated. Secondly, @annehulsey is correct, once you see the page refreshing you won't see the calendar month change until it finds a spot.

**Comment by nedmi** [comment]
Thanks Annehulsey Alex,  where/how  do i get 10.1
Cheers
Nedmi

**Comment by alexDrinkwater** [comment]
@nedmi Refer to the link on the readme

![image](https://user-images.githubusercontent.com/7938031/126389220-e4af1d8d-d3fb-493d-b00d-318c8bb77d80.png)

**Comment by nedmi** [comment]
Thanks Alex I got it all good Cheers
Nedmi
