### ISSUE TITLE
App not triggering on selected myDates

### ISSUE THREAD

**Issue by ricoboirn** [jvolker/miq-nz-booking-tools#63]
Hi Alex & Jeremias

I'm just wondering why  the script/app didn't recognized the available dates.  Ive just missed 5 attempts recently.
 Needing any dates in between Aug 1-12, 2021. I'm using latest version of master tool and MIQ-Booking-Assistance v0.10.1.
Here's the script I've been running.

// CHANGE DATES TO WHAT YOU ARE LOOKING FOR
let myDates = ['2021-8-12', '2021-8-11', '2021-8-10', '2021-8-9', '2021-8-8', '2021-8-7', '2021-8-6', '2021-8-5', '2021-8-4', '2021-8-3, '2021-8-2', '2021-8-1'];

// DON'T CARE ABOUT A SPECIFIC DATE? SET THIS TO TRUE
let findAnyDate = false;

Ive tried with the app version but same result, no trigger with the selected date.
I've done simulating the dates and its just working fine. Does the date selection script only works with the window fully maximized and window selected? My MIQ chromium is opened in my 2nd monitor and Im busy with something on my main monitor.

**Comment by alexDrinkwater** [comment]
@ricoboirn maybe it's because the room criteria you set in the step before the calendar doesn't match what's available?

**Comment by ricoboirn** [comment]
Ive checked it and they do match.

let accessibilityRequirement = false; // change to "true" if you have accessibility requirement
let roomType = 'double'; // double or twin

![image](https://user-images.githubusercontent.com/20818064/126406453-6a2a29c6-d65d-45de-8efb-9a2ed0ab7275.png)

Now, I removed all myDates and hoping for any available date just to see if any its the problem. 
I'm wondering if its my 1440p resolution interfering with the script, now i kept it opened on my 2nd monitor with 1080p.

**Comment by ricoboirn** [comment]
It appears like app/script doesn't work if you input any specific dates but it just works as intended if you dont input any specific dates.

**Comment by alexDrinkwater** [comment]
I'm pretty sure I addressed the issue where if you select specific dates there was no alert in #75, reopen if you still have issues with v0.10.2.
