### ISSUE TITLE
App not changing from July

### ISSUE THREAD

**Issue by Saj22** [jvolker/miq-nz-booking-tools#64]
Hi

I am trying your new script today and selected month of August.  However month keeps refreshing on July - it does not go to August.  Will it go to August if a spot becomes available?  Also tried any date for a while but nothing came up - just kept refreshing on July.  Is that because no dates became available at all?

**Comment by Saj22** [comment]
Forgot to say....thanks for this awesome script.  I have spent weeks trying to book the normal way with no success.

**Comment by jiajiada1005** [comment]
Well, I got the same problem.

**Comment by MannerlyApple94** [comment]
@Saj22 @jiajiada1005 This is expected behaviour. It will only change from July if a date within the given range is found (it will change to the month with the earliest available date matching the input).

**Comment by alexDrinkwater** [comment]
This is expected behavior, it will only switch month once a date is found.
