### ISSUE TITLE
Script calendar cycle issue?

### ISSUE THREAD

**Issue by danieldjw101** [jvolker/miq-nz-booking-tools#65]
Firstly, thanks for all the work you're putting into this. The script is fantastic and its the first time I have genuinely felt I might be able to secure a spot!

I have been running the v0.9.0 script (CLI) for the last 5 days looking for dates in September, after yesterdays website change I have downloaded the latest v0.10.1 release.

With the previous version when the refresh cycle started I would see the calendar on the page cycle across to September and either alert if a date was available or pause until the next refresh. Since the latest update the calendar doesn't move away from July for me. It stays at July until the next refresh.

I have been able to replicate this behavior on two different Windows devices which both worked with v0.9.0. I see the same behavior regardless of the findAnyDate settings and in both App/CLI.

Not sure if this is impacting others, any ideas?

**Comment by Anwere** [comment]
I'm seeing the same thing.

**Comment by Saj22** [comment]
Me too.  You just put it more clearer than I did - thank you.  I feel the same - maybe I can finally get a spot.  Just discovered this script yesterday (shortly before the change) and am now living in hope!!

**Comment by ricoboirn** [comment]
@danieldjw101  I'm having the same issue. Ive missed 4 attempts few hours ago. Dates shown available but script didn't kick in, page kept on refreshing and didn't  auto selected the date for me. Hoping Jeremias and Alex will be able to find the culprit.

**Comment by Anwere** [comment]
I know it's 'How Long Is That Piece Of String?' but I've been running it solid for two days, no hits whatsoever.

**Comment by ricoboirn** [comment]
It appears like the script for specific date selection doesnt work but if you dont set a specific date date it works. Ive just got a hit on a random date and its auto selected, stop refreshing.

**Comment by Anwere** [comment]
Ditto that just got my first hit with no date(s) selected.

Was gone before I could even click Next but.

**Comment by danieldjw101** [comment]
Ok perhaps this is just a change in behavior in version v0.10.1 and the calendar doesn't need to visibly cycle to detect the dates?

**Comment by Saj22** [comment]
So when you get a hit it jump to the date is that correct?

**Comment by ricoboirn** [comment]
@Saj22 @danieldjw101 yes.

**Comment by Anwere** [comment]
It did for me (but was gone in a second or so)

![image](https://user-images.githubusercontent.com/87685739/126423407-8c10ffcd-b007-48a2-8fb4-c2ea99ef1877.png)

**Comment by Saj22** [comment]
Since yesterday, with the changes on MIQ, I have had to click next 3 times before it will move on.  Anyone else with the same issue?

**Comment by dvilsbosss** [comment]
Thank you for the all your help.

Since the changes to the MIQ website the refresh rate was done way down. From 2/3 times a minute to once every 3/4 mins. The date selection & restart search options dont work. Select month section work better instead of a target date. Also it only beeps now if the window it active. Anyway a new update is on the works ???

**Comment by jvolker** [comment]
@Saj22 and @dvilsbosss could you please open a separate issue? (@dvilsbosss in that new issue, could you please add info on where you read about those rate changes?) Thanks.

**Comment by alexDrinkwater** [comment]
Hi Everyone, I will try take a look at the issues mentioned this evening.

**Comment by alexDrinkwater** [comment]
I'm pretty sure I addressed the issue where if you select specific dates there was no alert in #75, reopen if you still have issues with v0.10.2.
