### ISSUE TITLE
No longer recognizing the webpage, or reloading the page

### ISSUE THREAD

**Issue by jooknon** [jvolker/miq-nz-booking-tools#67]
I'm using the downloaded Windows version. It worked for about 6 hours today, but within the last hour it stopped refreshing. I exited and relaunched the program. It still will not recognize that I have logged in and am at the Hold Allocation page. 

Booking Assistance window still has header "A new browser window should appear. Please navigate to "Secure your allocation" page."

Have tried changing dates, and reloading the allocation page but it makes no difference. 

 - Operating System: Windows 10 Home
 - Version: MIQ-Booking-Assistance 0.10.1
![Capture](https://user-images.githubusercontent.com/87770572/126565502-5724933c-c36c-41d8-bd08-6b7043c27d7b.JPG)

**Comment by cummins070** [comment]
I just downloaded a new version this morning and it's been running fine all day. I guess you could try that?

**Comment by jooknon** [comment]
redownloaded and installed hours later and it working now.

**Comment by Randhirmo** [comment]
Where did you download I can't see that?
