### ISSUE TITLE
Is it possible for the MIQ Booking Assistance app to miss alerts?

### ISSUE THREAD

**Issue by Anwere** [jvolker/miq-nz-booking-tools#68]
Not sure if this is an actual bug or just a case of things falling between the cracks so to speak, but I've been running the app near constantly for several days now and during that time have only had a single alert.

I just randomly glanced Twitter and saw that the @allmiqdates account had just reported a slot but I didn't get any alert ('beep') at my end. Maybe it just came in between the refresh and was missed? Or is it a case of the requirements (room / number of people) not matching? I've set those at single room to cast the net as wide as possible.

Edit: actually I've seen quite a few from today that didn't trigger on the app

Just hoping it's not a fault with the app at my end or something, getting kinda desperate to be honest so would hate to miss any chances.

![image](https://user-images.githubusercontent.com/87685739/126605299-4f73eca9-3b0a-4354-860d-9d6b0cd0457b.png)
![image](https://user-images.githubusercontent.com/87685739/126605104-85b19c41-5a89-41e8-85a0-710512e274ff.png)

**Comment by Anwere** [comment]
Ps. I'm in Thailand hence the time-zone difference (-5hrs) but as you can see the tweeted alert was 7:40PM which would've been 2:40PM here

**Comment by acidack** [comment]
I have this issue too when I filtered by dates. Not getting any alerts in fact compared to the twitter results. I have it running to check every 5 seconds. 
I did get some results when I left it unfiltered.

**Comment by alexDrinkwater** [comment]
I'm pretty sure I addressed the issue where if you select specific dates there was no alert in #75, reopen if you still have issues with v0.10.2.
