### ISSUE TITLE
Electron app

### ISSUE THREAD

**Issue by alexDrinkwater** [jvolker/miq-nz-booking-tools#7]
What do you thinking about making the booking helper into an electron app so that people don't need to install node? We could add a setting panel to control the variables.

**Comment by jvolker** [comment]
I actually had a similar thing in mind at the start. Just never found the time to improve it further. I think it sounds like a great idea. This would make the tool available to all people without coding skills.

Would you like to work on a PR for this?

**Comment by alexDrinkwater** [comment]
@jvolker I was wondering if you had any thoughts on the PR, is it going the direction you were thinking?

**Comment by jvolker** [comment]
@alexDrinkwater yes, it does. Thanks so much!! I commented more in the PR.
