### ISSUE TITLE
Frozen at Found "Secure your allocation" page! 

### ISSUE THREAD

**Issue by HKG2301** [jvolker/miq-nz-booking-tools#70]
v 10.1 just stopped running a couple of hours ago. Reloading, restarting, etc no change. Gets to the Found "Secure your allocation" page! then nothing. No auto-refresh of the 'Selected your intended arrival date' page.

Maybe a coincidence, but the Android MIQ app stopped working about the same time, returning a m.j: HTTP 400 response error code.

![image_2021-07-23_152359](https://user-images.githubusercontent.com/87677692/126734160-a7e01165-67f7-48b0-be21-41586e1eb90d.png)

**Comment by alistairgraham** [comment]
I just opened an issue for the same thing woops. As I mention, I think it's because it's waiting for an element that never exists anymore on this line here:
https://github.com/jvolker/miq-nz-booking-tools/blob/5966bb7928e3ce1f273cf978746b6a1595ee915f/MIQ-Booking-Assistance/miq-assistance.js#L113

They must have updated their website to change the class name or something.

**Comment by cummins070** [comment]
> v 10.1 just stopped running a couple of hours ago. Reloading, restarting, etc no change. Gets to the Found "Secure your allocation" page! then nothing. No auto-refresh of the 'Selected your intended arrival date' page.
> 
> Maybe a coincidence, but the Android MIQ app stopped working about the same time, returning a m.j: HTTP 400 response error code.
> 
> ![image_2021-07-23_152359](https://user-images.githubusercontent.com/87677692/126734160-a7e01165-67f7-48b0-be21-41586e1eb90d.png)

Where does a bro find the Android MIQ app?

**Comment by HKG2301** [comment]
Hey bro, it’s on PlayStore. Just search for MIQ Refresh by Sergey Buzin.  From: cummins070Sent: 23 July 2021 15:46To: jvolker/miq-nz-booking-toolsCc: HKG2301; AuthorSubject: Re: [jvolker/miq-nz-booking-tools] Frozen at Found "Secure your allocation" page! (#70) v 10.1 just stopped running a couple of hours ago. Reloading, restarting, etc no change. Gets to the Found "Secure your allocation" page! then nothing. No auto-refresh of the 'Selected your intended arrival date' page.Maybe a coincidence, but the Android MIQ app stopped working about the same time, returning a m.j: HTTP 400 response error code.Where does a bro find the Android MIQ app?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jvolker** [comment]
> I just opened an issue for the same thing woops. As I mention, I think it's because it's waiting for an element that never exists anymore on this line here:
> https://github.com/jvolker/miq-nz-booking-tools/blob/5966bb7928e3ce1f273cf978746b6a1595ee915f/MIQ-Booking-Assistance/miq-assistance.js#L113
> 
> They must have updated their website to change the class name or something.

Yes. Closing this in favour of #71.
