### ISSUE TITLE
Stopped working after MIQ website update

### ISSUE THREAD

**Issue by alistairgraham** [jvolker/miq-nz-booking-tools#71]
miq-nz-booking-assistance-Windows-v0.10.1.exe has stopped refreshing the page. I think it might be because it's waiting for an element with the class `.flatpickr-input` to exist but it never exists now?
https://github.com/jvolker/miq-nz-booking-tools/blob/5966bb7928e3ce1f273cf978746b6a1595ee915f/MIQ-Booking-Assistance/miq-assistance.js#L113

**Comment by Hijzij** [comment]
Have the same problem: stopped working as off 1430hrs NZtime Friday 23July.
Closed and restarted programme: no success
Restarted laptop: no success
Removed app and reloaded: no success.......
Hopefully some-one can help us.

**Comment by acidack** [comment]
yeap they've changed the way the backend once again making it harder to scrape.. none of the tools are working currently as a result.

**Comment by cummins070** [comment]
Same problem here, it was working earlier today, had it running all day (based in the US). Hopefully it's an easy fix!

**Comment by necastroz** [comment]
I got this issue ...... any help  ?   Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-3juv2Ft1FaY3xWYNGXExi9oTqA3RQ4gGhU='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by Lyannel12** [comment]
same help please.. :(

**Comment by nedmi** [comment]
I also have not been able to get back online line as well checked 9.0 it also does not scan the month request

**Comment by stilljake** [comment]
The MIQ website has been updated and all the flatpickr calendar elements have changed. 
<img width="421" alt="Screenshot 2021-07-23 at 05 05 53" src="https://user-images.githubusercontent.com/22511726/126754283-a6bfcc34-9b67-4fc2-89cd-d05367c79c63.png">

You are correct @alistairgraham  in thinking `.flatpickr-input` never exists because it doesn't anymore. Probably this was an attempt by them to combat bots. 

They have done the same thing to the calendar at https://allocation.miq.govt.nz/portal/ so none of the tools will work anymore. 

The MIQ date notifications twitter bot is broken too.

I managed to check the page source when a date became available and it seems like they are also now obfuscating `'data-arrival-dates'` which means the current method of for checking for dates matches will no longer work either.
<img width="403" alt="Screenshot 2021-07-23 at 05 08 44" src="https://user-images.githubusercontent.com/22511726/126754517-485972d0-22ae-4cbf-aca0-5d5a18ae42cf.png">

**Comment by jvolker** [comment]
> miq-nz-booking-assistance-Windows-v0.10.1.exe has stopped refreshing the page. I think it might be because it's waiting for an element with the class `.flatpickr-input` to exist but it never exists now?
> https://github.com/jvolker/miq-nz-booking-tools/blob/5966bb7928e3ce1f273cf978746b6a1595ee915f/MIQ-Booking-Assistance/miq-assistance.js#L113

Looks like the calendar has `id="accommodation-calendar"` now. Maybe it's possible to check for any dates that do not have the class `q14-disabled`?

![image](https://user-images.githubusercontent.com/546852/126755085-06adc8e7-b5b7-4362-877b-ce0c07901ef2.png)

Please only comment here if you have any new information. It really helps anyone working on improving/fixing this tool to not get a flood of messages. Thanks.

**Comment by stilljake** [comment]
> Looks like the calendar has `id="accommodation-calendar"` now. Maybe it's possible to check for any dates that do not have the class `q14-disabled`?

It looks like unique class tags are being generated for each session

<img width="362" alt="Screenshot 2021-07-23 at 10 23 02" src="https://user-images.githubusercontent.com/22511726/126756002-a67c0680-c2c7-48a7-a3f6-cdd1f8e1f99e.png">
and see my previous comment where it shows `s9r`

**Comment by MannerlyApple94** [comment]
> and see my previous comment where it shows `s9r`

Not sure if this helps, but it seems it cycles through a limited number of class tags, at least for me, the only variations I'm getting are:
- s9r-day
- yyh-day
- bki-day
- g10-day
- it7-day
- vv8-day
- mi4-day

**Comment by nz029** [comment]
i have a script that is running fine, would you need that mate?

**Comment by cummins070** [comment]
> i have a script that is running fine, would you need that mate?

Sharing caring :)

**Comment by alistairgraham** [comment]
@MannerlyApple94 I've had a look at the CSS and there are 8 combinations. The eighth is `q14-day`.

**Comment by dvilsbosss** [comment]
> i have a script that is running fine, would you need that mate?

@nz029 hopefully its still working. waiting for you to share.

**Comment by alexDrinkwater** [comment]
@nz029 Can you create a PR?

**Comment by alexDrinkwater** [comment]
Here is the method that parses the data-arrival-dates attribute.

```
                key: "getAvailableDates",
                value: function() {
                    if (this.calendarElement.getAttribute("data-arrival-dates").length <= 0)
                        return [];
                    for (var e = [], t = [58501527, 28741588, 61219430, 20294527, 57613046, 20913046, 23093500, 40765602], n = this.calendarElement.getAttribute("data-arrival-dates").split("_"), a = 0; a < n.length; a++) {
                        n[a] = n[a].split("").reverse().join(""),
                        n[a] = "" + (Number(n[a]) - t[a % t.length]);
                        var i = n[a].substring(0, 4) + "-" + n[a].substring(4, 6) + "-" + n[a].substring(6, 8);
                        e.includes(i) || e.push(i)
                    }
                    var o = r()(this.getMaxDate(), "YYYY-MM-DD");
                    return e.filter((function(e) {
                        return r()(e, "YYYY-MM-DD") < o
                    }
                    ))
                }
```

I'm assuming the  t = [58501527, 28741588, 61219430, 20294527, 57613046, 20913046, 23093500, 40765602] array will be unique to each session or refresh.

**Comment by nz029** [comment]
> @nz029 Can you create a PR?

i am a civil engineer alex.... know nothing about coding or the coding language. But necessity can teach you anything..... haha
what do you mean by PR? :/ :(

PS: I haven't created that that script, just using it.
I have messaged it to jvolker on twitter

**Comment by alexDrinkwater** [comment]
@nz029 Thanks nz029. Not sure which twitter handle you used because jvolker on twitter is a different person to on github. Either way I think I've got a fix that bypasses miq spoofing the css classes.

**Comment by nz029** [comment]
> @nz029 Thanks nz029. Not sure which twitter handle you used because jvolker on twitter is a different person to on github. Either way I think I've got a fix that bypasses miq spoofing the css classes.

I sent it to the correct handle mentioned on his profile.
https://twitter.com/jeremiasvolker

**Comment by alexDrinkwater** [comment]
> > @nz029 Thanks nz029. Not sure which twitter handle you used because jvolker on twitter is a different person to on github. Either way I think I've got a fix that bypasses miq spoofing the css classes.
> 
> I sent it to the correct handle mentioned on his profile.
> https://twitter.com/jeremiasvolker

**Comment by jvolker** [comment]
Thanks a lot, everyone, for fixing the script! Especially @alexDrinkwater for implementing the fix and creating a new release.

I did receive the script on Twitter but have been off for 1.5 days. Please post anything related to this script here instead. Then everyone can work with it right away.
