### ISSUE TITLE
MIQ web site is logging me out for lack of activity

### ISSUE THREAD

**Issue by andrewgill28mvp** [jvolker/miq-nz-booking-tools#72]
The MIQ web site is logging me out for lack of activity whilst the app is running. The app appears unchanged. Is this right or should we click the continue button which comes up each time?

Thanks,

Andrew

**Describe your problem**

**Steps you have taken so far**
 

**Screenshots**

**Your system (please complete the following information):**
 - Operating System: 
 - Version:

**Comment by andrewgill28mvp** [comment]
We are new so nervous if the app is not in fact working we are 'going nowhere'! We are in Uk and have a special visa. The app seems to be running but the MIQ site on our screen is logging out saying lack of activity.![image](https://user-images.githubusercontent.com/87844761/126745312-b7dfe7a9-230b-449e-92f6-3c89f862dc1a.jpeg) here's a screen shot of how the app looks. We have the latest version of windows.

**Comment by stephengraham1** [comment]
jvolker, to add to the above.
However, first I would just like to say, very much appreciate your application!! You are helping, thank you!!
I have been running your app a few days but no success yet, unfortunately.
Early hours of this morning (UK time), the app stopped refreshing. Therefore, after a period of time the site logged me out.
I rebooted my system, downloaded the .exe file again (miq-nz-booking-assistance-Windows-v0.10.1) and have tried a few times this morning. Everything seems the same, but when the script is rinning it just stops refreshing.
OS Name: Microsoft Windows 10 Home Single Language
Version: 10.0.19042 Build 19042
Laptop: HP ENVY x360 Convertible 13 ar0xxx
System Type: x64-based PC
Google Chrome Version: Version 92.0.4515.107 (Official Build) (64-bit)

Your help is greatly appreciated!
![Screenshot_23-07-2021-AM](https://user-images.githubusercontent.com/57229007/126755036-88baab36-25e4-4184-9fd6-dba0df82ef3d.jpg)
![Screenshot2_23-07-2021-AM](https://user-images.githubusercontent.com/57229007/126755090-f4e23a1f-3d44-4a39-bee1-16b7977220ab.jpg)

**Comment by stilljake** [comment]
Yep. The website has been updated and none of the tools will work currently. See: https://github.com/jvolker/miq-nz-booking-tools/issues/71#issuecomment-885476509
