### ISSUE TITLE
Seems like the app froze

### ISSUE THREAD

**Issue by papstuc** [jvolker/miq-nz-booking-tools#74]
So in another issue (https://github.com/jvolker/miq-nz-booking-tools/issues/68) I saw that the under the "Found "Secure your allocation" page! Wait for beep sound, then select date and continue booking." text there is a log how many times MIQ servers got checked.

I am using this app for straight up 7 hours now and nothing appeard

![Screenshot_14](https://user-images.githubusercontent.com/45045063/126821688-88fd0138-a13e-40ae-8dd6-42eb0867f3d5.png)

it's looking like this for some time now but doesn't log or anything else. 

Am I doing something wrong?

**Comment by Bsul1** [comment]
https://github.com/jvolker/miq-nz-booking-tools/issues/71

**Comment by alexDrinkwater** [comment]
Fixed by #75
