### ISSUE TITLE
Apple version

### ISSUE THREAD

**Issue by Hijzij** [jvolker/miq-nz-booking-tools#77]
Hi Alex / Jeremiah,

Thanks for solving the issue which started yesterday; your effort is highly appreciated.
And apologies for my impatience, but can we expect an apple version of the latest release, or do I need to start searching the internet for another script?

Thanks,
André

**Comment by alexDrinkwater** [comment]
@jvolker Can you build and upload an apple version?

**Comment by jvolker** [comment]
I've just uploaded the macOS release. Sorry for the delay. I've been off for 1.5 days. 

I'm going to have another look into automated releases to avoid this issue in the future.

**Comment by Hijzij** [comment]
No need to apologise Jeremias; what you guys are doing in your spare time is awesome!
Danke,
André
