### ISSUE TITLE
Latest script not jumping to date

### ISSUE THREAD

**Issue by Saj22** [jvolker/miq-nz-booking-tools#78]
**Describe your problem**

**Steps you have taken so far**
 

**Screenshots**

**Your system (please complete the following information):**
 - Operating System: 
 - Version: 
Alarm goes off but it doesn't jump to the date

**Comment by Saj22** [comment]
Version: 0.10.2
Windows 10

**Comment by jvolker** [comment]
Closing this in favour of #86.
