### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by shawry292** [jvolker/miq-nz-booking-tools#8]
Getting an 403 Forbidden error after about 5 - 10 mins of runtime. Domain is probably detecting too much activity. 

Is anyone else getting these?

**Comment by jvolker** [comment]
I remember getting those too. Just waiting for a little bit before restarting always solved it for me. 

It would be a nice feature to have the script automatically detect this error and take a break.

**Comment by shawry292** [comment]
Yeah, will look into adding some time delays. Or detect for that line of text etc

**Comment by Andy-3336** [comment]
Hi guys

Getting 403 forbidden as well. Any ideas on how to overcome this

**Comment by MrShroomfish** [comment]
Hey guys,

Thanks so much for all your hard work!

I too am getting this 403 error. Like others have said, when it happens I need to wait anywhere between 1 and 5 mins before I can restart the script. 

I am happy to provide more info if someone is trying to diagnose this!

**Comment by rpalexander** [comment]
Came across this as well and was able to get around it by adjusting the time between refreshes. Changing it to 5 seconds seemed to refresh frequently enough without triggering the timeout error. Hope this helps :)

**Comment by jvolker** [comment]
> Changing it to 5 seconds seemed to refresh frequently enough without triggering the timeout error.

Thanks. That worked for me too. I just changed the default to 5s for now.

**Comment by MrShroomfish** [comment]
Thanks guys this worked great!

 I tried different times and even 4.5s causes the 403, so I think 5 is perfect.

**Comment by roweboat** [comment]
Still getting this on the released version. Any chance you could expose the retry interval on the settings page? BTW this is a great tool! We're trying really hard to get a spot for a family member to return from the UK.

**Comment by nedmi** [comment]
HI also got the 403 forbidden today

**Comment by alexDrinkwater** [comment]
@roweboat yeah, can do.

**Comment by nedmi** [comment]
Thanks for response Alex, I see the requirement to just reload  when you get kicked off the MIQ calendar page. 
Thanks for all you and Volker are doing. I am hoping to get back in November .
cheers

**Comment by crazichicken** [comment]
> > Changing it to 5 seconds seemed to refresh frequently enough without triggering the timeout error.
> 
> Thanks. That worked for me too. I just changed the default to 5s for now.

Thanks so much @jvolker & @alexDrinkwater for all your work, we really appreciate it! Can you please expose the refresh interval on the MacOS settings page? I'm still getting 403 Forbidden, perhaps the default refresh interval hasn't been updated for MacOS?

**Comment by alexDrinkwater** [comment]
Users can now select their refresh interval
