### ISSUE TITLE
App Stopped Working - Signed in but doesn't refresh anymore

### ISSUE THREAD

**Issue by natashajtk** [jvolker/miq-nz-booking-tools#83]
Hi All - I am having issues with the app no longer refreshing... 

Stopped working about two day ago, have tried downloading latest version and reinstalling. 

I login, and go to set dates as before, but there is no option to "restart search" and it won't start by itself....

Anyone have any tips on what I'm doing wrong? It was working before.

Thanks !! (screenshot below)

![image](https://user-images.githubusercontent.com/87370276/126912601-04d937ee-a2b6-4f7f-b424-2a457e2381bb.png)

**Comment by Yokai** [comment]
See issues 81 - I think that there;s a change that they have made on the Booking site...

**Comment by alexDrinkwater** [comment]
Hi @natashajtk, please make sure you are on the latest version of the application v0.10.2 or later. MIQ website updated twice recently.

**Comment by tbgoose** [comment]
@alexDrinkwater Hi Alex

I'm definitely using the latest version and doesn't seem to advance to specified dates on initial search. If I change dates etc again the restart search button is always greyed out.
It seems to be having trouble with the date/calendar part still. Does 0.10.2 work for November on your end?

**Comment by alexDrinkwater** [comment]
@tbgoose The calendar does not switch month until a date is found. The restart search button is only enabled after a date is found and you miss it. It is working great for November.

**Comment by natashajtk** [comment]
@tbgoose <https://github.com/tbgoose> Hi, no it’s not that, it’s that the
page is no longer refreshing every 5 seconds for me like it was before. i
know the new update stayed on july unless it found a month, but it’s just
staying on the originally opened page…

**Comment by natashajtk** [comment]
I've reinstalled it again this morning and th page seems to be refreshing again now - fingers crossed! Ahh I understand so if I put the dates in I don't need to restart it, only once a date has been found. Great! Thanks for the help everyone!
