### ISSUE TITLE
Couldn't get the App to work, the command line method will not go to set dates.

### ISSUE THREAD

**Issue by Champenoislevrai** [jvolker/miq-nz-booking-tools#84]
Started with the app v. 0.10.2
with a lot of trouble getting the search button to work after entering dates,

So I went to method 2 using the latest master download (~3 hours ago)
It refreshes as per the setting, but stays on the July calendar page, miq-assistance.js is set to go to specific dates in Oct.

The command window is showing:
... (\miq-nz-booking-tools-master\MIQ-Booking-ssistance\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:151:21)
at WaitTask.rerun (miq-nz-booking-tools-master\MIQ-Booking-Assistance\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:528:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Win10 Pro
v. 21H1

I've read, searched and gone through most of the issues.
Any help appreciated.

**Comment by alexDrinkwater** [comment]
@Champenoislevrai The calendar staying on July is normal behavior. The script doesn't need to switch the month to find the dates. But if it does find a date it will switch to that date for you, and select the date.

**Comment by nz029** [comment]
> @Champenoislevrai The calendar staying on July is normal behavior. The script doesn't need to switch the month to find the dates. But if it does find a date it will switch to that date for you, and select the date.

Hi Alex, it is not switching and selecting the date. I can confirm that.

**Comment by Champenoislevrai** [comment]
Yes, I can confirm that is not happening
I've spent all day on it today, if a date becomes available as entered in miq-assistance.js
the screen has to be manually taken to the month and it's not obvious which the date is when you get there.

**Comment by jvolker** [comment]
This has also been reported in #78 .

**Comment by jvolker** [comment]
There is a long conversation about this topic in #86. I'm closing this in favour of this other issue.
