### ISSUE TITLE
No "npm i" in folder

### ISSUE THREAD

**Issue by Andy-3336** [jvolker/miq-nz-booking-tools#9]
Hi Guys.
Not a coder or anything like that but trying to book MIQ for my daughter.
I have followed instructions but the npm I does not appear in the MIQ-Bookings-Assistance folder.

Any suggestions.

Working on a Mac

Thanking you in advance

Andy

**Comment by jvolker** [comment]
It sounds like you are looking for a folder or file called `npm i`. But it's actually a command you have to type in on the command line.

This is what you have to do on a Mac:
1. **Open the command line, called "Terminal" on a Mac:** press CMD + SPACE to open Spotlight search. Type in `Terminal`, it should find the Terminal (command line) app. Press `ENTER` to open it.
2. **Navigate into the downloaded directory:** type `cd ` into the command line window and drag'n' drop the MIQ-Bookings-Assistance folder into the command line window. It should read like that: `cd /PATH/TO/YOUR/FOLDER` and press `ENTER`
3. **Install software packages the code depends on ("dependencies"):** type in `npm i` and press ENTER.

Hope this helps.

**Comment by Andy-3336** [comment]
Hi Mr Volker. Thank you for your email. Did what you said when I run script nothing seems to happen when I log into the MIQ site. Doesn’t auto fill No. we are looking for space in November . Does the script make provision for this

Thank you once again fir your help

Andy

[Andy Anderson](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=141366)	[141366]
Regards

Andy

0824564169

On July 10, 2021 at 20:19 GMT, Jeremias Volker ***@***.***> wrote:

It sounds like you are looking for a folder or file called npm i. But it's actually a command you have to type in on the command line.

This is what you have to do on a Mac:

- Open the command line, called "Terminal" on a Mac: press CMD + SPACE to open Spotlight search. Type in Terminal, it should find the Terminal (command line) app. Press ENTER to open it.
- Navigate into the downloaded directory: type cd  into the command line window and drag'n' drop the MIQ-Bookings-Assistance folder into the command line window. It should read like that: cd /PATH/TO/YOUR/FOLDER and press ENTER
- Install software packages the code depends on ("dependencies"): type in npm i and press ENTER.

Hope this helps.

**Comment by jvolker** [comment]
Could you please describe in more detail what steps you have taken, what you expect and how what you see is differing from your expectations?

> we are looking for space in November . Does the script make provision for this

Yes, this can be configured in the code. You just need to change [one number](https://github.com/jvolker/miq-nz-booking-tools/blob/7bd0069fd585db42e0018cacfa04a5c6aa822104/MIQ-Booking-Assistance/index.js#L5).

**Comment by Andy-3336** [comment]
Hi Jeremias

This is what I have changed

Month = 11
refresh 20 1500

Not sure if there is anything else

Thank you once again for your help

Andy

[image: Screenshot 2021-07-14 at 11.08.54.png]

**Comment by jvolker** [comment]
Not sure how this looks like in your code `refresh 20 1500` but it seems off. It's best to leave this line as it was.

Could you please copy and paste the line of `Month = 11` directly from your code? If you describe your code here it's best to copy and paste it here directly.

**Comment by jvolker** [comment]
You might like to give the binary release a try which we just released (big thanks to @alexDrinkwater): https://github.com/jvolker/miq-nz-booking-tools/releases/latest You don't need to code for that.

Feel free to reopen if you have more questions.
