### ISSUE TITLE
You have been temporarily blocked due to excessive page refreshes, or other unusual activity

### ISSUE THREAD

**Issue by orotau** [jvolker/miq-nz-booking-tools#94]
**Describe the bug**
Logged out after about 1 hour (658 times on 5 sec refresh). With error message as per screenshot

**Screenshots**
![Screen Shot 2021-07-29 at 9 06 51 AM](https://user-images.githubusercontent.com/6657957/127396747-091b3232-0821-4e56-9482-95e2990288cb.png)

**Your system (please complete the following information):**
macOS 11.4
MIQ-Booking-Assistance 0.10.2

**Comment by jvolker** [comment]
Thanks for reporting it. The same error has been mentioned in #89 before and seems related. I'm closing this in favour of the other issue.
