### ISSUE TITLE
I have no idea how to use this tool .just can't figure out where to start.can anyone help pls

### ISSUE THREAD

**Issue by 31031958** [jvolker/miq-nz-booking-tools#97]
I have no idea how to use this tool .just can't figure out where to start.can anyone help pls

**Comment by jvolker** [comment]
Download from here: https://github.com/jvolker/miq-nz-booking-tools/releases/latest
Read the user guide: https://github.com/jvolker/miq-nz-booking-tools/blob/master/MIQ-Booking-Assistance/README.md

If you have more specific questions feel free to reopen this issue.

**Comment by 31031958** [comment]
Hi  there
Thanks for email.
Unfortunately I'm not tek savey with this stuff. Saw the github site from a
NZ stuff news report  and thought it might help me get my isolation room .
I clicked on the link in your email but cant not see where or how to
download wat ever it is I have to download.
My phone is a old samsung S4 .
Just need some guidance please.
Hope you can help help
Owen
Uk

**Comment by stilljake** [comment]
Hey Owen,

This is a not a mobile application, so you will need to download the `miq-nz-booking-assistance-Windows-v0.10.3.exe` file on to a windows computer or `miq-nz-booking-assistance-macOS-v0.10.3.zip` on mac. Then you should be able to follow along with the user guide.

**Comment by 31031958** [comment]
Hi Jacob
Thanks for the information.
Unfortunately I only have my phone and chromebook laptop.
I've been trying to secure a isolation room for months but never seem to be
in time or quick enough. Seems so unfair as I only want to get home to NZ.
Why the hell MIQ don't use a queing system is crazy in my mind. At least
everyone trying to get back would have some sort of plan and time frame to
make plans but this allocation system is pants.
Thanks again for your help
Owen
